In [4]:
import os
import json
import pandas as pd
import psycopg2
import plotly.express as px

In [5]:
#aggre_insurance

path1="C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/aggregated/insurance/country/india/state/"

aggre_insur_list=os.listdir(path1)

columns1={"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[], "Transaction_amount":[]}

for state in aggre_insur_list:
    cur_states=path1+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            A=json.load(data)

            for i in A["data"]['transactionData']:
                name=i["name"]
                count=i["paymentInstruments"][0]["count"]
                amount=i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amount)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))

aggre_insurance=pd.DataFrame(columns1)

aggre_insurance["States"]=aggre_insurance["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggre_insurance["States"]=aggre_insurance["States"].str.replace("-"," ")
aggre_insurance["States"]=aggre_insurance["States"].str.title()
aggre_insurance["States"]=aggre_insurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/aggregated/insurance/country/india/state/'

In [ ]:
#aggre_transaction

path2="C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/aggregated/transaction/country/india/state/"

agg_tran_list= os.listdir(path2)

columns2={"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[], "Transaction_amount":[]}

for state in agg_tran_list:
    cur_states=path2+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            B=json.load(data)

            for i in B["data"]['transactionData']:
                name=i["name"]
                count=i["paymentInstruments"][0]["count"]
                amount=i["paymentInstruments"][0]["amount"]
                columns2["Transaction_type"].append(name)
                columns2["Transaction_count"].append(count)
                columns2["Transaction_amount"].append(amount)
                columns2["States"].append(state)
                columns2["Years"].append(year)
                columns2["Quarter"].append(int(file.strip(".json")))

aggre_transation=pd.DataFrame(columns2)  

aggre_transation["States"]=aggre_transation["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggre_transation["States"]=aggre_transation["States"].str.replace("-"," ")
aggre_transation["States"]=aggre_transation["States"].str.title()
aggre_transation["States"]=aggre_transation["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#aggre_user

path3="C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/aggregated/user/country/india/state/"

agg_user_list= os.listdir(path3)

columns3={"States":[], "Years":[], "Quarter":[], "Brands":[], "Transaction_count":[], "Percentage":[]}

for state in agg_user_list:
    cur_states=path3+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            C=json.load(data)

            try:
                for i in C["data"]['usersByDevice']:
                    brand=i["brand"]
                    count=i["count"]
                    percentage=i["percentage"]
                    columns3["Brands"].append(brand)
                    columns3["Transaction_count"].append(count)
                    columns3["Percentage"].append(percentage)
                    columns3["States"].append(state)
                    columns3["Years"].append(year)
                    columns3["Quarter"].append(int(file.strip(".json")))

            except:
                pass

aggre_user=pd.DataFrame(columns3)

aggre_user["States"]=aggre_user["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
aggre_user["States"]=aggre_user["States"].str.replace("-"," ")
aggre_user["States"]=aggre_user["States"].str.title()
aggre_user["States"]=aggre_user["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#map_insurance

path4= "C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/map/insurance/hover/country/india/state/"

map_insur_list=os.listdir(path4)


columns4={"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[], "Transaction_amount":[]}

for state in map_insur_list:
    cur_states=path4+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            D=json.load(data)
            
            for i in D["data"]['hoverDataList']:
                    name=i["name"]
                    count=i['metric'][0]["count"]
                    amount=i['metric'][0]["amount"]
                    columns4["Districts"].append(name)
                    columns4["Transaction_count"].append(count)
                    columns4["Transaction_amount"].append(amount)
                    columns4["States"].append(state)
                    columns4["Years"].append(year)
                    columns4["Quarter"].append(int(file.strip(".json")))

map_insurance=pd.DataFrame(columns4)

map_insurance["States"]=map_insurance["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_insurance["States"]=map_insurance["States"].str.replace("-"," ")
map_insurance["States"]=map_insurance["States"].str.title()
map_insurance["States"]=map_insurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#map_transaction

path5= "C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/map/transaction/hover/country/india/state/"

map_tran_list= os.listdir(path5)

columns5={"States":[], "Years":[], "Quarter":[], "Districts":[], "Transaction_count":[], "Transaction_amount":[]}

for state in map_tran_list:
    cur_states=path5+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            E=json.load(data)
            
            for i in E["data"]['hoverDataList']:
                    name=i["name"]
                    count=i['metric'][0]["count"]
                    amount=i['metric'][0]["amount"]
                    columns5["Districts"].append(name)
                    columns5["Transaction_count"].append(count)
                    columns5["Transaction_amount"].append(amount)
                    columns5["States"].append(state)
                    columns5["Years"].append(year)
                    columns5["Quarter"].append(int(file.strip(".json")))


map_tran=pd.DataFrame(columns5)

map_tran["States"]=map_tran["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_tran["States"]=map_tran["States"].str.replace("-"," ")
map_tran["States"]=map_tran["States"].str.title()
map_tran["States"]=map_tran["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#map_user

path6= "C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/map/user/hover/country/india/state/"

map_user= os.listdir(path6)

columns6={"States":[], "Years":[], "Quarter":[], "Districts":[], "RegisteredUsers":[], "AppOpens":[]}

for state in map_user:
    cur_states=path6+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            F=json.load(data)

            for i in F["data"]['hoverData'].items():
                
                district=i[0]
                registeredUsers=i[1]['registeredUsers']
                appOpens=i[1]['appOpens']
                columns6["Districts"].append( district)
                columns6["RegisteredUsers"].append(registeredUsers)
                columns6["AppOpens"].append(appOpens)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

map_user=pd.DataFrame(columns6)

map_user["States"]=map_user["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
map_user["States"]=map_user["States"].str.replace("-"," ")
map_user["States"]=map_user["States"].str.title()
map_user["States"]=map_user["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#top insurance

path7="C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/top/insurance/country/india/state/"

top_insur_list=os.listdir(path7)

columns7={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_insur_list:
    cur_states=path7+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            G=json.load(data)

            for i in G["data"]["pincodes"]:
                
                entityname=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                columns7["Pincodes"].append(entityname)
                columns7["Transaction_count"].append(count)
                columns7["Transaction_amount"].append(amount)
                columns7["States"].append(state)
                columns7["Years"].append(year)
                columns7["Quarter"].append(int(file.strip(".json")))

top_insurance=pd.DataFrame(columns7)


top_insurance["States"]=top_insurance["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_insurance["States"]=top_insurance["States"].str.replace("-"," ")
top_insurance["States"]=top_insurance["States"].str.title()
top_insurance["States"]=top_insurance["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#top_transaction

path8="C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/top/transaction/country/india/state/"

top_tran_list=os.listdir(path8)

columns8={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}

for state in top_tran_list:
    cur_states=path8+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            H=json.load(data)

            for i in H["data"]["pincodes"]:
                
                entityname=i["entityName"]
                count=i["metric"]["count"]
                amount=i["metric"]["amount"]
                columns8["Pincodes"].append(entityname)
                columns8["Transaction_count"].append(count)
                columns8["Transaction_amount"].append(amount)
                columns8["States"].append(state)
                columns8["Years"].append(year)
                columns8["Quarter"].append(int(file.strip(".json")))

top_transaction=pd.DataFrame(columns8)  


top_transaction["States"]=top_transaction["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_transaction["States"]=top_transaction["States"].str.replace("-"," ")
top_transaction["States"]=top_transaction["States"].str.title()
top_transaction["States"]=top_transaction["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#top_user

path9="C:/Users/Aravind Chirshtopher/Desktop/Youtube Project/phonepe project/pulse/data/top/user/country/india/state/"

top_user_list=os.listdir(path9)

columns9={"States":[], "Years":[], "Quarter":[], "Pincodes":[], "RegisteredUsers":[]}

for state in top_user_list:
    cur_states=path9+state+"/"
    agg_year_list=os.listdir(cur_states)
    
    for year in agg_year_list:
        cur_year=cur_states+year+"/"
        agg_file_list=os.listdir(cur_year)
       
        for file in agg_file_list:
            cur_file=cur_year+file
            data=open(cur_file,"r")

            I=json.load(data)

            for i in I["data"]["pincodes"]:
                
                entityname=i["name"]
                registeredusers=i["registeredUsers"]
                columns9["Pincodes"].append(entityname)
                columns9["RegisteredUsers"].append( registeredusers)
                columns9["States"].append(state)
                columns9["Years"].append(year)
                columns9["Quarter"].append(int(file.strip(".json")))

top_user=pd.DataFrame(columns9)

top_user["States"]=top_user["States"].str.replace('andaman-&-nicobar-islands','Andaman & Nicobar')
top_user["States"]=top_user["States"].str.replace("-"," ")
top_user["States"]=top_user["States"].str.title()
top_user["States"]=top_user["States"].str.replace('Dadra & Nagar Haveli & Daman & Diu','Dadra and Nagar Haveli and Daman and Diu')

In [ ]:
#Table Creation

#SQL connection

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()

#aggregated_insurance_table

create_query_1='''CREATE TABLE if not exists aggregated_insurance(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Transaction_type varchar(250),
                                                      Transaction_count bigint,
                                                      Transaction_amount bigint)'''

cursor.execute(create_query_1)
mydb.commit()

insert_query_1='''INSERT INTO aggregated_insurance(States, Years, Quarter, Transaction_type, Transaction_count,
                                                    Transaction_amount)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =aggre_insurance.values.tolist()
cursor.executemany(insert_query_1,data)

mydb.commit()

In [ ]:
aggre_insurance.values.tolist()

[['Andaman & Nicobar', '2020', 2, 'Insurance', 6, 1360.0],
 ['Andaman & Nicobar', '2020', 3, 'Insurance', 41, 15380.0],
 ['Andaman & Nicobar', '2020', 4, 'Insurance', 124, 157975.0],
 ['Andaman & Nicobar', '2021', 1, 'Insurance', 225, 244266.0],
 ['Andaman & Nicobar', '2021', 2, 'Insurance', 137, 181504.0],
 ['Andaman & Nicobar', '2021', 3, 'Insurance', 230, 305235.0],
 ['Andaman & Nicobar', '2021', 4, 'Insurance', 757, 1056380.0],
 ['Andaman & Nicobar', '2022', 1, 'Insurance', 768, 1131287.0],
 ['Andaman & Nicobar', '2022', 2, 'Insurance', 501, 779740.0],
 ['Andaman & Nicobar', '2022', 3, 'Insurance', 643, 902466.0],
 ['Andaman & Nicobar', '2022', 4, 'Insurance', 901, 1441210.0],
 ['Andaman & Nicobar', '2023', 1, 'Insurance', 1004, 1439198.0],
 ['Andaman & Nicobar', '2023', 2, 'Insurance', 768, 1233395.0],
 ['Andaman & Nicobar', '2023', 3, 'Insurance', 795, 1251145.0],
 ['Andhra Pradesh', '2020', 2, 'Insurance', 22104, 3982391.0],
 ['Andhra Pradesh', '2020', 3, 'Insurance', 49812, 12426481.0],
 ['Andhra Pradesh', '2020', 4, 'Insurance', 21464, 12985632.0],
 ['Andhra Pradesh', '2021', 1, 'Insurance', 22105, 12749874.0],
 ['Andhra Pradesh', '2021', 2, 'Insurance', 33205, 22730687.0],
 ['Andhra Pradesh', '2021', 3, 'Insurance', 23075, 19914338.0],
 ['Andhra Pradesh', '2021', 4, 'Insurance', 25423, 31610335.0],
 ['Andhra Pradesh', '2022', 1, 'Insurance', 29954, 42648157.0],
 ['Andhra Pradesh', '2022', 2, 'Insurance', 32185, 41708072.0],
 ['Andhra Pradesh', '2022', 3, 'Insurance', 39301, 48791931.0],
 ['Andhra Pradesh', '2022', 4, 'Insurance', 44329, 58043239.0],
 ['Andhra Pradesh', '2023', 1, 'Insurance', 34920, 51963355.0],
 ['Andhra Pradesh', '2023', 2, 'Insurance', 36376, 52067478.0],
 ['Andhra Pradesh', '2023', 3, 'Insurance', 43150, 57802396.0],
 ['Arunachal Pradesh', '2020', 2, 'Insurance', 65, 14329.0],
 ['Arunachal Pradesh', '2020', 3, 'Insurance', 135, 39687.0],
 ['Arunachal Pradesh', '2020', 4, 'Insurance', 125, 84247.0],
 ['Arunachal Pradesh', '2021', 1, 'Insurance', 194, 131611.0],
 ['Arunachal Pradesh', '2021', 2, 'Insurance', 204, 224928.0],
 ['Arunachal Pradesh', '2021', 3, 'Insurance', 212, 371051.0],
 ['Arunachal Pradesh', '2021', 4, 'Insurance', 320, 598459.0],
 ['Arunachal Pradesh', '2022', 1, 'Insurance', 355, 894107.0],
 ['Arunachal Pradesh', '2022', 2, 'Insurance', 564, 1360231.0],
 ['Arunachal Pradesh', '2022', 3, 'Insurance', 510, 1300304.0],
 ['Arunachal Pradesh', '2022', 4, 'Insurance', 613, 1464572.0],
 ['Arunachal Pradesh', '2023', 1, 'Insurance', 606, 1747475.0],
 ['Arunachal Pradesh', '2023', 2, 'Insurance', 696, 2095988.0],
 ['Arunachal Pradesh', '2023', 3, 'Insurance', 718, 1904786.0],
 ['Assam', '2020', 2, 'Insurance', 978, 210034.0],
 ['Assam', '2020', 3, 'Insurance', 2206, 599450.0],
 ['Assam', '2020', 4, 'Insurance', 2413, 1806801.0],
 ['Assam', '2021', 1, 'Insurance', 3167, 2334419.0],
 ['Assam', '2021', 2, 'Insurance', 3265, 3008122.0],
 ['Assam', '2021', 3, 'Insurance', 4495, 6010865.0],
 ['Assam', '2021', 4, 'Insurance', 8622, 13962068.0],
 ['Assam', '2022', 1, 'Insurance', 16230, 27447766.0],
 ['Assam', '2022', 2, 'Insurance', 9228, 15357811.0],
 ['Assam', '2022', 3, 'Insurance', 14149, 22543564.0],
 ['Assam', '2022', 4, 'Insurance', 18826, 29239168.0],
 ['Assam', '2023', 1, 'Insurance', 22100, 36963888.0],
 ['Assam', '2023', 2, 'Insurance', 16475, 28368139.0],
 ['Assam', '2023', 3, 'Insurance', 22593, 35618158.0],
 ['Bihar', '2020', 2, 'Insurance', 2816, 595621.0],
 ['Bihar', '2020', 3, 'Insurance', 9733, 2161102.0],
 ['Bihar', '2020', 4, 'Insurance', 9913, 7860932.0],
 ['Bihar', '2021', 1, 'Insurance', 12554, 8796619.0],
 ['Bihar', '2021', 2, 'Insurance', 14301, 13301581.0],
 ['Bihar', '2021', 3, 'Insurance', 18030, 18234941.0],
 ['Bihar', '2021', 4, 'Insurance', 22456, 27313813.0],
 ['Bihar', '2022', 1, 'Insurance', 20253, 27755736.0],
 ['Bihar', '2022', 2, 'Insurance', 21892, 28212833.0],
 ['Bihar', '2022', 3, 'Insurance', 28511, 34704251.0],
 ['Bihar', '2022', 4, 'Insurance', 33895, 43914519.0],
 ['Bihar', '2023', 1, 'Insurance', 26929, 38746711.0],
 ['Bihar', '2023', 2, 'Insurance', 29212, 40354886.0],
 ['Bihar', '2023', 3, 'Insurance', 36550, 45832355.0],
 ['Chandigarh', '2020', 2, 'Insurance', 149, 29537.0],
 ['Chandigarh', '2020', 3, 'Insurance', 264, 70969.0],
 ['Chandigarh', '2020', 4, 'Insurance', 200, 153341.0],
 ['Chandigarh', '2021', 1, 'Insurance', 338, 238576.0],
 ['Chandigarh', '2021', 2, 'Insurance', 378, 310943.0],
 ['Chandigarh', '2021', 3, 'Insurance', 494, 469634.0],
 ['Chandigarh', '2021', 4, 'Insurance', 710, 835813.0],
 ['Chandigarh', '2022', 1, 'Insurance', 792, 1150932.0],
 ['Chandigarh', '2022', 2, 'Insurance', 1330, 1874959.0],
 ['Chandigarh', '2022', 3, 'Insurance', 1533, 1998439.0],
 ['Chandigarh', '2022', 4, 'Insurance', 1403, 2024528.0],
 ['Chandigarh', '2023', 1, 'Insurance', 1520, 2415574.0],
 ['Chandigarh', '2023', 2, 'Insurance', 1704, 2501107.0],
 ['Chandigarh', '2023', 3, 'Insurance', 1883, 2660630.0],
 ['Chhattisgarh', '2020', 2, 'Insurance', 1346, 279005.0],
 ['Chhattisgarh', '2020', 3, 'Insurance', 4702, 1393656.0],
 ['Chhattisgarh', '2020', 4, 'Insurance', 3757, 2249901.0],
 ['Chhattisgarh', '2021', 1, 'Insurance', 4712, 2620468.0],
 ['Chhattisgarh', '2021', 2, 'Insurance', 5055, 3813417.0],
 ['Chhattisgarh', '2021', 3, 'Insurance', 4676, 3568837.0],
 ['Chhattisgarh', '2021', 4, 'Insurance', 6029, 8229039.0],
 ['Chhattisgarh', '2022', 1, 'Insurance', 6612, 10139190.0],
 ['Chhattisgarh', '2022', 2, 'Insurance', 7008, 10119964.0],
 ['Chhattisgarh', '2022', 3, 'Insurance', 8849, 12119470.0],
 ['Chhattisgarh', '2022', 4, 'Insurance', 11994, 18137856.0],
 ['Chhattisgarh', '2023', 1, 'Insurance', 10460, 16577191.0],
 ['Chhattisgarh', '2023', 2, 'Insurance', 10514, 16389610.0],
 ['Chhattisgarh', '2023', 3, 'Insurance', 11927, 17838382.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2020',
  2,
  'Insurance',
  651,
  101029.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2020',
  3,
  'Insurance',
  257,
  65504.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2020',
  4,
  'Insurance',
  232,
  149513.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  1,
  'Insurance',
  467,
  285691.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  2,
  'Insurance',
  368,
  275638.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  3,
  'Insurance',
  360,
  273596.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2021',
  4,
  'Insurance',
  421,
  425384.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  1,
  'Insurance',
  493,
  720741.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  2,
  'Insurance',
  438,
  686857.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  3,
  'Insurance',
  707,
  983776.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2022',
  4,
  'Insurance',
  871,
  1272628.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  1,
  'Insurance',
  799,
  1215168.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  2,
  'Insurance',
  694,
  1058753.0],
 ['Dadra and Nagar Haveli and Daman and Diu',
  '2023',
  3,
  'Insurance',
  969,
  1333103.0],
 ['Delhi', '2020', 2, 'Insurance', 11716, 1897480.0],
 ['Delhi', '2020', 3, 'Insurance', 7588, 1927285.0],
 ['Delhi', '2020', 4, 'Insurance', 9725, 8045442.0],
 ['Delhi', '2021', 1, 'Insurance', 12822, 9655261.0],
 ['Delhi', '2021', 2, 'Insurance', 13292, 10840929.0],
 ['Delhi', '2021', 3, 'Insurance', 16679, 15007079.0],
 ['Delhi', '2021', 4, 'Insurance', 34251, 36578331.0],
 ['Delhi', '2022', 1, 'Insurance', 28232, 35442069.0],
 ['Delhi', '2022', 2, 'Insurance', 26378, 31787281.0],
 ['Delhi', '2022', 3, 'Insurance', 35944, 41570160.0],
 ['Delhi', '2022', 4, 'Insurance', 48908, 60603173.0],
 ['Delhi', '2023', 1, 'Insurance', 45821, 61040038.0],
 ['Delhi', '2023', 2, 'Insurance', 41358, 54951108.0],
 ['Delhi', '2023', 3, 'Insurance', 47113, 58878500.0],
 ['Goa', '2020', 2, 'Insurance', 341, 71100.0],
 ['Goa', '2020', 3, 'Insurance', 683, 196864.0],
 ['Goa', '2020', 4, 'Insurance', 614, 682364.0],
 ['Goa', '2021', 1, 'Insurance', 879, 827384.0],
 ['Goa', '2021', 2, 'Insurance', 1016, 1028339.0],
 ['Goa', '2021', 3, 'Insurance', 1214, 1385986.0],
 ['Goa', '2021', 4, 'Insurance', 2087, 2737316.0],
 ['Goa', '2022', 1, 'Insurance', 2634, 3865245.0],
 ['Goa', '2022', 2, 'Insurance', 3524, 5093510.0],
 ['Goa', '2022', 3, 'Insurance', 3157, 4142108.0],
 ['Goa', '2022', 4, 'Insurance', 4388, 6190669.0],
 ['Goa', '2023', 1, 'Insurance', 4097, 5859549.0],
 ['Goa', '2023', 2, 'Insurance', 4166, 5930801.0],
 ['Goa', '2023', 3, 'Insurance', 3927, 5646054.0],
 ['Gujarat', '2020', 2, 'Insurance', 7697, 1430591.0],
 ['Gujarat', '2020', 3, 'Insurance', 12525, 3335812.0],
 ['Gujarat', '2020', 4, 'Insurance', 9990, 6055037.0],
 ['Gujarat', '2021', 1, 'Insurance', 12673, 7288104.0],
 ['Gujarat', '2021', 2, 'Insurance', 14676, 10263998.0],
 ['Gujarat', '2021', 3, 'Insurance', 15348, 12341903.0],
 ['Gujarat', '2021', 4, 'Insurance', 19142, 23282921.0],
 ['Gujarat', '2022', 1, 'Insurance', 22221, 29953433.0],
 ['Gujarat', '2022', 2, 'Insurance', 25381, 32090965.0],
 ['Gujarat', '2022', 3, 'Insurance', 31302, 37557227.0],
 ['Gujarat', '2022', 4, 'Insurance', 36418, 50629325.0],
 ['Gujarat', '2023', 1, 'Insurance', 32600, 46937694.0],
 ['Gujarat', '2023', 2, 'Insurance', 32484, 46254095.0],
 ['Gujarat', '2023', 3, 'Insurance', 51049, 65768085.0],
 ['Haryana', '2020', 2, 'Insurance', 6321, 1179814.0],
 ['Haryana', '2020', 3, 'Insurance', 7139, 1884868.0],
 ['Haryana', '2020', 4, 'Insurance', 8283, 5974278.0],
 ['Haryana', '2021', 1, 'Insurance', 11038, 7297880.0],
 ['Haryana', '2021', 2, 'Insurance', 12516, 11272453.0],
 ['Haryana', '2021', 3, 'Insurance', 14163, 13215898.0],
 ['Haryana', '2021', 4, 'Insurance', 19489, 25885838.0],
 ['Haryana', '2022', 1, 'Insurance', 22783, 32526943.0],
 ['Haryana', '2022', 2, 'Insurance', 25352, 33759068.0],
 ['Haryana', '2022', 3, 'Insurance', 35346, 45402800.0],
 ['Haryana', '2022', 4, 'Insurance', 37971, 56627115.0],
 ['Haryana', '2023', 1, 'Insurance', 37287, 61127194.0],
 ['Haryana', '2023', 2, 'Insurance', 40710, 62186066.0],
 ['Haryana', '2023', 3, 'Insurance', 42815, 61782311.0],
 ['Himachal Pradesh', '2020', 2, 'Insurance', 392, 77936.0],
 ['Himachal Pradesh', '2020', 3, 'Insurance', 531, 165559.0],
 ['Himachal Pradesh', '2020', 4, 'Insurance', 710, 630966.0],
 ['Himachal Pradesh', '2021', 1, 'Insurance', 1064, 906492.0],
 ['Himachal Pradesh', '2021', 2, 'Insurance', 1210, 1402338.0],
 ['Himachal Pradesh', '2021', 3, 'Insurance', 1759, 2444545.0],
 ['Himachal Pradesh', '2021', 4, 'Insurance', 2474, 4667661.0],
 ['Himachal Pradesh', '2022', 1, 'Insurance', 2768, 5234739.0],
 ['Himachal Pradesh', '2022', 2, 'Insurance', 2831, 5371078.0],
 ['Himachal Pradesh', '2022', 3, 'Insurance', 3641, 6161692.0],
 ['Himachal Pradesh', '2022', 4, 'Insurance', 4565, 9060436.0],
 ['Himachal Pradesh', '2023', 1, 'Insurance', 3909, 7826133.0],
 ['Himachal Pradesh', '2023', 2, 'Insurance', 4197, 8499425.0],
 ['Himachal Pradesh', '2023', 3, 'Insurance', 3935, 7869767.0],
 ['Jammu & Kashmir', '2020', 2, 'Insurance', 206, 48484.0],
 ['Jammu & Kashmir', '2020', 3, 'Insurance', 441, 133339.0],
 ['Jammu & Kashmir', '2020', 4, 'Insurance', 647, 734861.0],
 ['Jammu & Kashmir', '2021', 1, 'Insurance', 1105, 1546288.0],
 ['Jammu & Kashmir', '2021', 2, 'Insurance', 1197, 1832089.0],
 ['Jammu & Kashmir', '2021', 3, 'Insurance', 1452, 2139133.0],
 ['Jammu & Kashmir', '2021', 4, 'Insurance', 3113, 5223317.0],
 ['Jammu & Kashmir', '2022', 1, 'Insurance', 3584, 7244267.0],
 ['Jammu & Kashmir', '2022', 2, 'Insurance', 4071, 7729792.0],
 ['Jammu & Kashmir', '2022', 3, 'Insurance', 4794, 8281826.0],
 ['Jammu & Kashmir', '2022', 4, 'Insurance', 5031, 10111183.0],
 ['Jammu & Kashmir', '2023', 1, 'Insurance', 4555, 10275877.0],
 ['Jammu & Kashmir', '2023', 2, 'Insurance', 5262, 10974839.0],
 ['Jammu & Kashmir', '2023', 3, 'Insurance', 5453, 10975874.0],
 ['Jharkhand', '2020', 2, 'Insurance', 2063, 405031.0],
 ['Jharkhand', '2020', 3, 'Insurance', 5368, 1349934.0],
 ['Jharkhand', '2020', 4, 'Insurance', 3659, 2857024.0],
 ['Jharkhand', '2021', 1, 'Insurance', 4879, 3274851.0],
 ['Jharkhand', '2021', 2, 'Insurance', 5180, 5084230.0],
 ['Jharkhand', '2021', 3, 'Insurance', 6794, 7046048.0],
 ['Jharkhand', '2021', 4, 'Insurance', 8465, 11190423.0],
 ['Jharkhand', '2022', 1, 'Insurance', 9373, 13819466.0],
 ['Jharkhand', '2022', 2, 'Insurance', 9477, 13464840.0],
 ['Jharkhand', '2022', 3, 'Insurance', 14388, 18156857.0],
 ['Jharkhand', '2022', 4, 'Insurance', 16779, 23147805.0],
 ['Jharkhand', '2023', 1, 'Insurance', 16108, 23823406.0],
 ['Jharkhand', '2023', 2, 'Insurance', 16662, 23216215.0],
 ['Jharkhand', '2023', 3, 'Insurance', 19478, 25165702.0],
 ['Karnataka', '2020', 2, 'Insurance', 27358, 4794150.0],
 ['Karnataka', '2020', 3, 'Insurance', 53701, 12407394.0],
 ['Karnataka', '2020', 4, 'Insurance', 31747, 26814968.0],
 ['Karnataka', '2021', 1, 'Insurance', 37595, 30183325.0],
 ['Karnataka', '2021', 2, 'Insurance', 40969, 39501006.0],
 ['Karnataka', '2021', 3, 'Insurance', 47468, 48078366.0],
 ['Karnataka', '2021', 4, 'Insurance', 74436, 90723288.0],
 ['Karnataka', '2022', 1, 'Insurance', 95640, 130733580.0],
 ['Karnataka', '2022', 2, 'Insurance', 93385, 123228632.0],
 ['Karnataka', '2022', 3, 'Insurance', 110273, 144605784.0],
 ['Karnataka', '2022', 4, 'Insurance', 133971, 185063287.0],
 ['Karnataka', '2023', 1, 'Insurance', 127376, 186543426.0],
 ['Karnataka', '2023', 2, 'Insurance', 117232, 175704013.0],
 ['Karnataka', '2023', 3, 'Insurance', 139699, 199448538.0],
 ['Kerala', '2020', 2, 'Insurance', 1588, 360216.0],
 ['Kerala', '2020', 3, 'Insurance', 8811, 2830361.0],
 ['Kerala', '2020', 4, 'Insurance', 5479, 4445525.0],
 ['Kerala', '2021', 1, 'Insurance', 5731, 5040506.0],
 ['Kerala', '2021', 2, 'Insurance', 9530, 9676588.0],
 ['Kerala', '2021', 3, 'Insurance', 10926, 13255646.0],
 ['Kerala', '2021', 4, 'Insurance', 19199, 31260319.0],
 ['Kerala', '2022', 1, 'Insurance', 37110, 64172190.0],
 ['Kerala', '2022', 2, 'Insurance', 35667, 59920203.0],
 ['Kerala', '2022', 3, 'Insurance', 54587, 85390924.0],
 ['Kerala', '2022', 4, 'Insurance', 65563, 103982997.0],
 ['Kerala', '2023', 1, 'Insurance', 62377, 101786828.0],
 ['Kerala', '2023', 2, 'Insurance', 61032, 100620604.0],
 ['Kerala', '2023', 3, 'Insurance', 66059, 110021582.0],
 ['Ladakh', '2020', 2, 'Insurance', 14, 2538.0],
 ['Ladakh', '2020', 3, 'Insurance', 33, 10260.0],
 ['Ladakh', '2020', 4, 'Insurance', 27, 34206.0],
 ['Ladakh', '2021', 1, 'Insurance', 32, 34530.0],
 ['Ladakh', '2021', 2, 'Insurance', 46, 86251.0],
 ['Ladakh', '2021', 3, 'Insurance', 192, 174052.0],
 ['Ladakh', '2021', 4, 'Insurance', 76, 195966.0],
 ['Ladakh', '2022', 1, 'Insurance', 75, 193935.0],
 ['Ladakh', '2022', 2, 'Insurance', 113, 269446.0],
 ['Ladakh', '2022', 3, 'Insurance', 137, 369742.0],
 ['Ladakh', '2022', 4, 'Insurance', 162, 410091.0],
 ['Ladakh', '2023', 1, 'Insurance', 161, 495736.0],
 ['Ladakh', '2023', 2, 'Insurance', 215, 635831.0],
 ['Ladakh', '2023', 3, 'Insurance', 232, 649027.0],
 ['Lakshadweep', '2020', 3, 'Insurance', 4, 1199.0],
 ['Lakshadweep', '2021', 1, 'Insurance', 4, 5225.0],
 ['Lakshadweep', '2021', 2, 'Insurance', 5, 6962.0],
 ['Lakshadweep', '2021', 3, 'Insurance', 19, 16034.0],
 ['Lakshadweep', '2021', 4, 'Insurance', 11, 17096.0],
 ['Lakshadweep', '2022', 1, 'Insurance', 27, 34664.0],
 ['Lakshadweep', '2022', 2, 'Insurance', 18, 27463.0],
 ['Lakshadweep', '2022', 3, 'Insurance', 38, 41504.0],
 ['Lakshadweep', '2022', 4, 'Insurance', 15, 27135.0],
 ['Lakshadweep', '2023', 1, 'Insurance', 26, 30199.0],
 ['Lakshadweep', '2023', 2, 'Insurance', 15, 38384.0],
 ['Lakshadweep', '2023', 3, 'Insurance', 12, 12407.0],
 ['Madhya Pradesh', '2020', 2, 'Insurance', 6283, 1198701.0],
 ['Madhya Pradesh', '2020', 3, 'Insurance', 14476, 3496126.0],
 ['Madhya Pradesh', '2020', 4, 'Insurance', 10653, 4897124.0],
 ['Madhya Pradesh', '2021', 1, 'Insurance', 14427, 5567927.0],
 ['Madhya Pradesh', '2021', 2, 'Insurance', 14803, 9787391.0],
 ['Madhya Pradesh', '2021', 3, 'Insurance', 11990, 7806258.0],
 ['Madhya Pradesh', '2021', 4, 'Insurance', 15069, 17524432.0],
 ['Madhya Pradesh', '2022', 1, 'Insurance', 13791, 19901462.0],
 ['Madhya Pradesh', '2022', 2, 'Insurance', 14629, 20159098.0],
 ['Madhya Pradesh', '2022', 3, 'Insurance', 22733, 29185118.0],
 ['Madhya Pradesh', '2022', 4, 'Insurance', 29234, 42712883.0],
 ['Madhya Pradesh', '2023', 1, 'Insurance', 26393, 45135679.0],
 ['Madhya Pradesh', '2023', 2, 'Insurance', 27027, 44871764.0],
 ['Madhya Pradesh', '2023', 3, 'Insurance', 29300, 46963348.0],
 ['Maharashtra', '2020', 2, 'Insurance', 39836, 6879717.0],
 ['Maharashtra', '2020', 3, 'Insurance', 71662, 19230156.0],
 ['Maharashtra', '2020', 4, 'Insurance', 44798, 27113814.0],
 ['Maharashtra', '2021', 1, 'Insurance', 55792, 33137753.0],
 ['Maharashtra', '2021', 2, 'Insurance', 70381, 46763103.0],
 ['Maharashtra', '2021', 3, 'Insurance', 52268, 41313307.0],
 ['Maharashtra', '2021', 4, 'Insurance', 82423, 93262227.0],
 ['Maharashtra', '2022', 1, 'Insurance', 88015, 117411928.0],
 ['Maharashtra', '2022', 2, 'Insurance', 80935, 104603934.0],
 ['Maharashtra', '2022', 3, 'Insurance', 90958, 113835208.0],
 ['Maharashtra', '2022', 4, 'Insurance', 125900, 174915648.0],
 ['Maharashtra', '2023', 1, 'Insurance', 112174, 166596248.0],
 ['Maharashtra', '2023', 2, 'Insurance', 102754, 157303399.0],
 ['Maharashtra', '2023', 3, 'Insurance', 104872, 151171882.0],
 ['Manipur', '2020', 2, 'Insurance', 55, 12554.0],
 ['Manipur', '2020', 3, 'Insurance', 134, 45164.0],
 ['Manipur', '2020', 4, 'Insurance', 90, 49057.0],
 ['Manipur', '2021', 1, 'Insurance', 136, 72254.0],
 ['Manipur', '2021', 2, 'Insurance', 127, 81332.0],
 ['Manipur', '2021', 3, 'Insurance', 111, 133016.0],
 ['Manipur', '2021', 4, 'Insurance', 145, 271789.0],
 ['Manipur', '2022', 1, 'Insurance', 177, 517854.0],
 ['Manipur', '2022', 2, 'Insurance', 218, 553649.0],
 ['Manipur', '2022', 3, 'Insurance', 200, 403213.0],
 ['Manipur', '2022', 4, 'Insurance', 271, 620655.0],
 ['Manipur', '2023', 1, 'Insurance', 222, 632084.0],
 ['Manipur', '2023', 2, 'Insurance', 123, 341671.0],
 ['Manipur', '2023', 3, 'Insurance', 76, 193021.0],
 ['Meghalaya', '2020', 2, 'Insurance', 41, 8829.0],
 ['Meghalaya', '2020', 3, 'Insurance', 112, 33615.0],
 ['Meghalaya', '2020', 4, 'Insurance', 92, 71029.0],
 ['Meghalaya', '2021', 1, 'Insurance', 107, 128776.0],
 ['Meghalaya', '2021', 2, 'Insurance', 139, 148434.0],
 ['Meghalaya', '2021', 3, 'Insurance', 139, 214554.0],
 ['Meghalaya', '2021', 4, 'Insurance', 263, 451612.0],
 ['Meghalaya', '2022', 1, 'Insurance', 337, 729211.0],
 ['Meghalaya', '2022', 2, 'Insurance', 379, 789094.0],
 ['Meghalaya', '2022', 3, 'Insurance', 600, 1039491.0],
 ['Meghalaya', '2022', 4, 'Insurance', 627, 1189529.0],
 ['Meghalaya', '2023', 1, 'Insurance', 562, 1187523.0],
 ['Meghalaya', '2023', 2, 'Insurance', 730, 1551577.0],
 ['Meghalaya', '2023', 3, 'Insurance', 809, 1728076.0],
 ['Mizoram', '2020', 2, 'Insurance', 31, 7322.0],
 ['Mizoram', '2020', 3, 'Insurance', 74, 24691.0],
 ['Mizoram', '2020', 4, 'Insurance', 81, 119124.0],
 ['Mizoram', '2021', 1, 'Insurance', 415, 302841.0],
 ['Mizoram', '2021', 2, 'Insurance', 187, 124805.0],
 ['Mizoram', '2021', 3, 'Insurance', 81, 83641.0],
 ['Mizoram', '2021', 4, 'Insurance', 100, 175847.0],
 ['Mizoram', '2022', 1, 'Insurance', 85, 189428.0],
 ['Mizoram', '2022', 2, 'Insurance', 76, 115090.0],
 ['Mizoram', '2022', 3, 'Insurance', 310, 471306.0],
 ['Mizoram', '2022', 4, 'Insurance', 350, 612551.0],
 ['Mizoram', '2023', 1, 'Insurance', 171, 326688.0],
 ['Mizoram', '2023', 2, 'Insurance', 119, 232928.0],
 ['Mizoram', '2023', 3, 'Insurance', 166, 271799.0],
 ['Nagaland', '2020', 2, 'Insurance', 41, 9791.0],
 ['Nagaland', '2020', 3, 'Insurance', 89, 20798.0],
 ['Nagaland', '2020', 4, 'Insurance', 62, 38836.0],
 ['Nagaland', '2021', 1, 'Insurance', 79, 42973.0],

In [ ]:
#aggregated_transaction_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_2='''CREATE TABLE if not exists aggregated_transaction(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Transaction_type varchar(250),
                                                      Transaction_count bigint,
                                                      Transaction_amount bigint)'''

cursor.execute(create_query_2)
mydb.commit()

insert_query_2='''INSERT INTO aggregated_transaction(States, Years, Quarter, Transaction_type, Transaction_count,
                                                    Transaction_amount)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =aggre_transation.values.tolist()
cursor.executemany(insert_query_2,data)

mydb.commit()

In [ ]:
#aggregated_user_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_3='''CREATE TABLE if not exists aggregated_user(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Brands varchar(250),
                                                      Transaction_count bigint,
                                                     Percentage float)'''

cursor.execute(create_query_3)
mydb.commit()

insert_query_3='''INSERT INTO aggregated_user(States, Years, Quarter, Brands, Transaction_count,
                                                    Percentage)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =aggre_user.values.tolist()
cursor.executemany(insert_query_3,data)

mydb.commit()

In [ ]:
#map_insurance_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_4='''CREATE TABLE if not exists map_insurance(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Districts varchar(250),
                                                      Transaction_count bigint,
                                                     Transaction_amount bigint)'''

cursor.execute(create_query_4)
mydb.commit()

insert_query_4='''INSERT INTO map_insurance(States, Years, Quarter, Districts, Transaction_count,
                                                    Transaction_amount)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =map_insurance.values.tolist()
cursor.executemany(insert_query_4,data)

mydb.commit()

In [ ]:
#map_transaction_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_5='''CREATE TABLE if not exists map_transaction(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Districts varchar(250),
                                                      Transaction_count bigint,
                                                     Transaction_amount bigint)'''

cursor.execute(create_query_5)
mydb.commit()

insert_query_5='''INSERT INTO map_transaction(States, Years, Quarter, Districts, Transaction_count,
                                                    Transaction_amount)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =map_tran.values.tolist()
cursor.executemany(insert_query_5,data)

mydb.commit()

In [ ]:
#map_user_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_6='''CREATE TABLE if not exists map_user(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Districts varchar(250),
                                                      RegisteredUsers bigint,
                                                     AppOpens bigint)'''

cursor.execute(create_query_6)
mydb.commit()

insert_query_6='''INSERT INTO map_user(States, Years, Quarter, Districts, RegisteredUsers,
                                                    AppOpens)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =map_user.values.tolist()
cursor.executemany(insert_query_6,data)

mydb.commit()

In [ ]:
#top_insurance_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_7='''CREATE TABLE if not exists top_insurance(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Pincodes int,
                                                      Transaction_count bigint,
                                                     Transaction_amount bigint)'''

cursor.execute(create_query_7)
mydb.commit()

insert_query_7='''INSERT INTO top_insurance(States, Years, Quarter, Pincodes, Transaction_count,
                                                    Transaction_amount)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =top_insurance.values.tolist()
cursor.executemany(insert_query_7,data)

mydb.commit()

In [ ]:
#top_transaction_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_8='''CREATE TABLE if not exists top_transaction(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Pincodes int,
                                                      Transaction_count bigint,
                                                     Transaction_amount bigint)'''

cursor.execute(create_query_8)
mydb.commit()

insert_query_8='''INSERT INTO top_transaction(States, Years, Quarter, Pincodes, Transaction_count,
                                                    Transaction_amount)

                                                   values(%s,%s,%s,%s,%s,%s)'''

data =top_transaction.values.tolist()
cursor.executemany(insert_query_8,data)

mydb.commit()

In [ ]:
#top_user_table

mydb= psycopg2.connect(host="localhost",
                       user= 'postgres',
                       database="phonepe-dataset",
                       password="Aravind#123",
                       port="5432")
cursor=mydb.cursor()


create_query_9='''CREATE TABLE if not exists top_user(States varchar(250),
                                                      Years int,
                                                      Quarter int,
                                                      Pincodes int,
                                                      RegisteredUsers bigint
                                                     )'''

cursor.execute(create_query_9)
mydb.commit()

insert_query_9='''INSERT INTO top_user(States, Years, Quarter, Pincodes, RegisteredUsers
                                                   )

                                                   values(%s,%s,%s,%s,%s)'''

data =top_user.values.tolist()
cursor.executemany(insert_query_9,data)

mydb.commit()